name: Triage
on:
  issues:
    types: [opened]

jobs:
  build:
    name: Triage
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/triage-action@0.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        label: needs-triage
